### ISSUE TITLE
GitHub actions don't seem to be running for new PRs?

### ISSUE THREAD

**Issue by SodaVolcano** [zazwaz12/CITS3200---National-Housing-Simulation#37]
See PR #36 , no code checks are performed. @ctmes

**Comment by ctmes** [comment]
Code check branch wasn't merged, waiting on reviewer (I think there was a merge conflict). Now reviewers have been reassigned (Reece and Tin Chi)

Since resolved and updated to account for new imports (dirsync, loguru). Modified a few files minorly; logging.py added type checking; created pyrightconfig.json minor file.

Currently the test for pytest fails w/error code 5, meaning there are no tests.
